/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './Pages/__root'
import { Route as HomeImport } from './Pages/Home'
import { Route as IndexImport } from './Pages/index'
import { Route as UsersIndexImport } from './Pages/Users/index'
import { Route as SignUpIndexImport } from './Pages/SignUp/index'
import { Route as LoginIndexImport } from './Pages/Login/index'
import { Route as BookTablesImport } from './Pages/Book/Tables'

// Create/Update Routes

const HomeRoute = HomeImport.update({
  path: '/Home',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const UsersIndexRoute = UsersIndexImport.update({
  path: '/Users/',
  getParentRoute: () => rootRoute,
} as any)

const SignUpIndexRoute = SignUpIndexImport.update({
  path: '/SignUp/',
  getParentRoute: () => rootRoute,
} as any)

const LoginIndexRoute = LoginIndexImport.update({
  path: '/Login/',
  getParentRoute: () => rootRoute,
} as any)

const BookTablesRoute = BookTablesImport.update({
  path: '/Book/Tables',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/Home': {
      preLoaderRoute: typeof HomeImport
      parentRoute: typeof rootRoute
    }
    '/Book/Tables': {
      preLoaderRoute: typeof BookTablesImport
      parentRoute: typeof rootRoute
    }
    '/Login/': {
      preLoaderRoute: typeof LoginIndexImport
      parentRoute: typeof rootRoute
    }
    '/SignUp/': {
      preLoaderRoute: typeof SignUpIndexImport
      parentRoute: typeof rootRoute
    }
    '/Users/': {
      preLoaderRoute: typeof UsersIndexImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren([
  IndexRoute,
  HomeRoute,
  BookTablesRoute,
  LoginIndexRoute,
  SignUpIndexRoute,
  UsersIndexRoute,
])

/* prettier-ignore-end */
